name: liglo
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  convex_bottom_bar: ^2.2.5
  flutter_neumorphic: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
  - family: Oswald
    fonts:
    - asset: fonts/Oswald-Regular.ttf
  - family: Orbitron
    fonts:
    - asset: fonts/Orbitron-Bold.ttf
  - family: Lemonada
    fonts:
    - asset: fonts/Lemonada-Medium.ttf
  - family: Museo
    fonts:
    - asset: fonts/MuseoModerno-SemiBold.ttf



  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
